# Generated by Django 6.0.2 on 2026-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_nombre_archivo_titulo_archivo_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=20)),
                ('grado_cursar', models.CharField(max_length=50)),
                ('archivo_pdf', models.FileField(upload_to='registros_inscripcion/')),
                ('fecha_llenado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
